### ISSUE TITLE
Add 2FA

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/smartcard-client-windows#6]
Add 2FA to the user authentication.
Maybe it could be requested from the server if this should be done.

**Comment by lukasmatusiewicz** [comment]
Scenario: The user is sending just a PIN without OTP and awaits, that privacyIDEA will ask for the OTP in the next step.
Response: The server triggers the challenges and asks for OTP in the message, but at the same time it encounters an error: `4031`.

The PI response looks as follows:

`    "detail": {
        "client_mode": "interactive",
        "loginmode": "privacyIDEA",
        "message": "please enter otp: ",
        "messages": [
            "please enter otp: "
        ],
        "multi_challenge": [
            {
                "client_mode": "interactive",
                "message": "please enter otp: ",
                "serial": "OATH00159D24",
                "transaction_id": "13606...996141",
                "type": "hotp"
            }
        ],
        "serial": "OATH0...9D24",
        "threadid": 13999...8608,
        "transaction_id": "136062...90996141",
        "transaction_ids": [
            "136062...0996141"
        ],
        "type": "hotp"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "error": {
            "code": 4031,
            "message": "Authentication failure. Wrong credentials"
        },
        "status": false
    },`


- Can the` POST /auth` endpoint process the multiple challenges at all?

- Check if `POST /auth` can contain the `transaction_id` as the parameter.

**Comment by nilsbehlen** [comment]
This functionality seems to be inhibited in the server, where `/auth` does not handle challenge-response properly
